-- MySQL Script generated by MySQL Workbench
-- Thu May  7 22:32:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Usuario` (
  `idUsuario` INT NOT NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `correoElectronico` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefonoFijo` BIGINT(45) NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `producto` (
  `idproducto` INT NOT NULL,
  `marca` VARCHAR(45) NULL,
  `linea` VARCHAR(45) NULL,
  `precio` BIGINT(45) NULL,
  `imagen` VARCHAR(100) NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedido` (
  `idpedido` INT NOT NULL,
  `fecha` DATETIME NULL,
  `producto_idproducto` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idpedido`, `producto_idproducto`, `Usuario_idUsuario`),
  INDEX `fk_pedido_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  INDEX `fk_pedido_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`computo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computo` (
  `idcomputo` INT NOT NULL,
  `tipoRed` VARCHAR(45) NULL,
  `RAM` VARCHAR(45) NULL,
  `procesador` VARCHAR(45) NULL,
  `almacenamiento` VARCHAR(45) NULL,
  PRIMARY KEY (`idcomputo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tablet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tablet` (
  `idtablet` INT NOT NULL,
  `pulgadas` VARCHAR(45) NULL,
  `computo_idcomputo` INT NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idtablet`, `computo_idcomputo`, `producto_idproducto`),
  INDEX `fk_tablet_computo1_idx` (`computo_idcomputo` ASC) VISIBLE,
  INDEX `fk_tablet_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_tablet_computo1`
    FOREIGN KEY (`computo_idcomputo`)
    REFERENCES `computo` (`idcomputo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tablet_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`camara`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camara` (
  `idcamara` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `tamañoPantalla` VARCHAR(45) NULL,
  `resolucion` VARCHAR(45) NULL,
  `camaracol` VARCHAR(45) NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idcamara`, `producto_idproducto`),
  INDEX `fk_camara_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_camara_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`celular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `celular` (
  `idcelular` INT NOT NULL,
  `pulgadas` VARCHAR(45) NULL,
  `computo_idcomputo` INT NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idcelular`, `computo_idcomputo`, `producto_idproducto`),
  INDEX `fk_celular_computo1_idx` (`computo_idcomputo` ASC) VISIBLE,
  INDEX `fk_celular_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_celular_computo1`
    FOREIGN KEY (`computo_idcomputo`)
    REFERENCES `computo` (`idcomputo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_celular_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`computador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computador` (
  `idcomputador` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `computo_idcomputo` INT NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idcomputador`, `computo_idcomputo`, `producto_idproducto`),
  INDEX `fk_computador_computo1_idx` (`computo_idcomputo` ASC) VISIBLE,
  INDEX `fk_computador_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_computador_computo1`
    FOREIGN KEY (`computo_idcomputo`)
    REFERENCES `computo` (`idcomputo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_computador_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consola` (
  `idconsola` INT NOT NULL,
  `marca` VARCHAR(45) NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idconsola`, `producto_idproducto`),
  INDEX `fk_consola_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_consola_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`metodoPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metodoPago` (
  `idmetodoPago` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `metodoPagocol` VARCHAR(45) NULL,
  `numeroTarjeta` VARCHAR(45) NULL,
  `dinero` BIGINT(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idmetodoPago`, `Usuario_idUsuario`),
  INDEX `fk_metodoPago_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_metodoPago_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
